### ISSUE TITLE
BMV2 support of CocoSketch

### ISSUE THREAD

**Issue by hansomesong** [yindazhang/CocoSketch#2]
Hi Yinda,

Thanks for sharing this excellent job within open source community!  We notice that the P4 implementation is targeted for Tofino switch. Is it possible to run the P4 code within BMv2 switch? If not, is it possible to share some guidelines for adaptation?

**Comment by yindazhang** [comment]
Sorry that we have not tested it on the BMV2 switch. Our P4 code implements the hardware-friendly CocoSketch that targets the hardware platforms. If you want to work on software platforms, I recommend using the basic CocoSketch.
